### ISSUE TITLE
Not an issue but rather a request for LRT tutorial the way you have shown here for deseq2 model matrix design  

### ISSUE THREAD

**Issue by kcmtest** [tavareshugo/tutorial_DESeq2_contrasts#4]
Not an issue but rather a request for LRT tutorial the way you have shown here for deseq2 model matrix design . 

I have some doubts when i'm running LRT 

This is my condition dataframe small subset
```
 dput(head(metadata,18))
structure(list(FAB = structure(c(1L, 1L, 1L, 1L, 6L, 2L, 6L, 
4L, 3L, 5L, 7L, 3L, 2L, 7L, 6L, 2L, 6L, 2L), .Label = c("C", 
"M0", "M1", "M2", "M3", "M4", "M5"), class = "factor")), row.names = c("H1", 
"H2", "H3", "H4", "TCGA-AB-2856", "TCGA-AB-2849", "TCGA-AB-2971", 
"TCGA-AB-2930", "TCGA-AB-2891", "TCGA-AB-2872", "TCGA-AB-2851", 
"TCGA-AB-3011", "TCGA-AB-2949", "TCGA-AB-2981", "TCGA-AB-2965", 
"TCGA-AB-2822", "TCGA-AB-2828", "TCGA-AB-2959"), class = "data.frame")
```

Now I m running LRT on this.  In pairwise comparison condition I can set the reference level as such 
`coldata$condition<- relevel(coldata$condition, ref = "H") where  `H` is my control set with whom I compare all other factors.

**Now if I have to do the same with LRT is it correct to set the reference level?** 

**Second doubt** 

If i have to run LRT using different reference level how to do that? 

```
dds <- DESeq(dds, reduced=~condition, test="LRT")
dds_lrt <- DESeq(dds, test="LRT", reduced = ~ 1)
```

**Comment by tavareshugo** [comment]
thanks for your question @krushnach80 
Your question is a little out of topic for this tutorial, which is focused on setting numeric contrasts when using the Wald tests. 

The LRT test is a little different, because rather than running a specific comparison/contrast, it compares models that include/exclude certain predictor variables. The LRT test is not designed for pairwise comparisons. 

In your case, if I understood your question correct, you want to use the Wald test but run the test multiple times once for each pairwise comparison of interest. You could achieve this by creating multiple results tables. If you only have one condition with a reference (control) level, then you can do something like this:

```r
# set the model design
design(dds) <- ~ condition

# run DESeq model fitting
dds <- DESeq(dds)

# loop through the coefficients and get the test result for each of them
pairwise_comparisons <- lapply(resultsNames(dds)[-1], 
                               function(i) results(dds, name = i, tidy = TRUE))

# do some tidying to bind everything into a single data.frame
names(pairwise_comparisons) <- resultsNames(dds)[-1]
dplyr::bind_rows(pairwise_comparisons, .id = "comparison")
```

If you want more help on this topic, I advise you post a question on the [Bioconductor support site](https://support.bioconductor.org/). Also note that if you do multiple contrasts like this, then you may need to correct your p-values again (see [this post](https://support.bioconductor.org/p/87671/)).

**Comment by tavareshugo** [comment]
Hi @krushnach80,

With the LRT test it doesn't matter which sample you use as a reference. Even if you change the reference group, you still get the same p-values every time. 
The LRT test tries to answer the question: does adding an extra predictor to my model (in your case condition) explain a significant amount of variation in the data, compared to a model that excludes that predictor? So, it's testing for _overall_ effects of the predictor. 

However, if you also want to get the log2(fold-change) (`log2FoldChange`) for each pairwise comparison, then you can use the code I included above (to get the log(fold-change) for each pair of samples compared to control), but only consider the p-values from the LRT test.

**Comment by krushnach80** [comment]
**LRT test tries to answer the question: does adding an extra predictor to my model (in your case condition) explain a significant amount of variation in the data, compared to a model that excludes that predictor? So, it's testing for overall effects of the predictor.** This statement 

```
cnts <- matrix(rnbinom(n=1000, mu=100, size=1/0.5), ncol=15)
cond <- factor(rep(1:3, each=5))
cond
# object construction
dds <- DESeqDataSetFromMatrix(cnts, DataFrame(cond), ~ cond)
# standard analysis (Default Wald test)
dds <- DESeq(dds)

res <- results(dds)
ddsLRT <- DESeq(dds, test="LRT", reduced= ~ 1)
```
```
head(resLRT)
log2 fold change (MLE): cond 3 vs 1 
LRT p-value: '~ cond' vs '~ 1' 
DataFrame with 6 rows and 6 columns
          baseMean     log2FoldChange             lfcSE              stat             pvalue              padj
         <numeric>          <numeric>         <numeric>         <numeric>          <numeric>         <numeric>
1 67.3988972572591  -1.50268224393899 0.667559520943578  5.41518177622996 0.0666972945658396 0.671050246079242
2 87.6490212203271  0.822112827109229 0.561521601876028  2.84146270899191  0.241537302892211 0.735590876989915
3 111.008679255241 -0.365683073056093   0.6200380354513 0.693363167505794  0.707030422392719 0.900033822416997
4 91.1637448059437   1.19541864333521 0.629377870647424  4.53611224020929  0.103513201870715 0.671050246079242
5 108.350554639251  0.156485551830496 0.734593939883716 0.129787626962667   0.93716697259227 0.986999797536055
6 89.5206013160673  0.124449688249353 0.564801583740488  1.19388874051197  0.550491165957045 0.834616674779738
> resultsNames(ddsLRT)
[1] "Intercept"   "cond_2_vs_1" "cond_3_vs_1"
```
Please can you explain me putting it in biological context here the statement which you have explained how LRT works where in my above example I have 3 condition , `cond`

**does adding an extra predictor to my model (in your case condition) explain a significant amount of variation in the data, compared to a model that excludes that predictor**

How shall i see the full vs reduced model here in this case what is my  **extra predictor to my model** and what is my **a model that excludes that predictor**. I have to go through lots of basic grad level maths trying to figure out the basic simplistic way to understand and explain as a biologist.

I would be really glad if you could explain me i have to run through lots of mental gymnastics trying to figure how its working

**Comment by tavareshugo** [comment]
Dear @krushnach80 
If these concepts are unclear to you I would recommend that you either 1) consult a local statistician/bioinformatician or 2) attend an RNA-seq analysis course (we run a course online, the next one is happening soon and there are still places available, you can [register here](https://training.cam.ac.uk/bioinformatics/event/4252901)).

In any case, to answer your questions: 

* The full model is the model that includes all the predictors (the variables we think affect gene expression). In your case the full model only contains one predictor and is `~ cond`. The reduced model is the model that excludes one (or more) predictors and is the model we want to compare the full model against. In your case, the reduced model is one that doesn't include any explanatory variables, so simply `~ 1`. So, what we're asking is whether `cond` explains any of the variation in expression seen across our samples. If `cond` does not affect a gene's expression, then a model with or without that explanatory variable will be the same. But if `cond` affects a gene's expression, then the full model should explain our gene expression data better than the null model (giving us a low p-value). In a more biological way, the LRT is asking whether there is an _overall_ effect of `cond` in gene expression (regardless of which samples are more highly/lowly expressed). 
* The intercept is chosen as the first level of the `cond` factor. By default it is alphabetical, but you can use the `relevel()` function to change the reference level (for example to set "control" as your reference level).
* The second and third column coefficient would be the difference of each group _always relative to the reference group_. So, in your example:
  * `cond1` is the `(Intercept)` or reference group
  * `cond2` is the term for the difference between `cond2` - `cond1`
  * `cond3` is the term for the difference between `cond3` - `cond1`
* Your last paragraph is correct: if you use the LRT you are obtaining genes that change their expression _regardless of which pairs of samples are different_ (you want to filter these based on `padj`). So, you can use that test to obtain generally interesting genes. Then, to get the magnitude (and direction - up or down) of the difference you can get pairwise  `log2FoldChange` for each comparison of interest - this might be interesting to then group (or cluster) the genes according to groups of up/down-regulated genes relative to control.

**Comment by krushnach80** [comment]
thank you i spent the day reading the basic concepts of regression modeling, now after reading your answer to my query it makes sense to me .Thank you again for clarifying
